[target.'cfg(all(target_arch = "x86_64"))']
rustflags = ["-C",
    "link-args=-Wl,-r,_proxy_done -Wl,-r,_proxy_http_call -Wl,-r,_proxy_dequeue_shared_queue -Wl,-r,_proxy_enqueue_shared_queue -Wl,-r,_proxy_register_shared_queue -Wl,-r,_proxy_set_property -Wl,-r,_proxy_resolve_shared_queue -Wl,-r,_proxy_get_property -Wl,-r,_proxy_get_header_map_pairs -Wl,-r,_proxy_get_buffer_bytes -Wl,-r,_proxy_get_current_time_nanoseconds"]
