[target.'cfg(all(target_arch = "x86_64"))']
rustflags = ["-C", "linker=clang","-C",
    "link-args= -r,_proxy_done -r,_proxy_http_call -r,_proxy_dequeue_shared_queue -r,_proxy_enqueue_shared_queue -r,_proxy_register_shared_queue -r,_proxy_set_property -r,_proxy_resolve_shared_queue -r,_proxy_get_property -r,_proxy_get_header_map_pairs -r,_proxy_get_buffer_bytes -r,_proxy_get_current_time_nanoseconds"]

