version: '3'

services:
  proxy:
    build: .
    volumes:
      - ./envoy-bootstrap-static-loading.yaml:/etc/envoy.yaml
      - ../../target/wasm32-wasi/release/authn_filter.wasm:/etc/oicd-filter.wasm
    ports:
      - 8090:10000
      - 19901:9901
    depends_on:
      - mock-oauth2-server
  mock-oauth2-server:
    image: docker.pkg.github.com/navikt/mock-oauth2-server/mock-oauth2-server:0.3.2
    ports:
      - 8888:8080
    environment:
      JSON_CONFIG_PATH: "/var/mock-auth2-config.json"
    volumes:
      - ./mock-auth2-config.json:/var/mock-auth2-config.json
  bin:
    image: kennethreitz/httpbin

  tool:
    image: praqma/network-multitool
    depends_on:
      - mock-oauth2-server
      - token-tester