name: build-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Install WASME"
      run: |
        curl -sL https://run.solo.io/wasme/install | sh
    - name: Build
      run: |
        rustup update
        rustup target add wasm32-unknown-unknown
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: "Set image version"
      id: set-image-tag
      run: |
        export FILTER_NAME="${BASEIMAGE}:$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
        echo "FILTER_NAME=${FILTER_NAME}" >> $GITHUB_ENV
        echo "::set-output name=FILTER_NAME::${FILTER_NAME}"
    - name: "Build WASM OCI image"
      run: make build-image
    - name: "Push WASM OCI image"
      run: |
        "~/.wasme/bin/wasme login -u $WASME_USERNAME -p $WASME_PASSWORD"
      env:
        "WASME_USERNAME": "${{ secrets.WASME_USERNAME }}"
        "WASME_PASSWORD": "${{ secrets.WASME_PASSWORD }}"
