name: build-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  "BASEIMAGE": "webassemblyhub.io/thesisworker/"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Install WASME"
      run: |
        curl -sL https://run.solo.io/wasme/install | sh
        echo "$HOME/.wasme/bin/" >> $GITHUB_PATH
    - name: Build
      run: |
        rustup update
        rustup target add wasm32-unknown-unknown
        make release
    - name: Run tests
      run: "echo TODO make tests work" #cargo test --verbose

    - name: "Build WASM OCI image"
      run: make build-image # -e IMAGE=${IMAGE}
    - name: "Push WASM OCI image"
      run: |
        "wasme login -u $WASME_USERNAME -p $WASME_PASSWORD"
        wasme push ${IMAGE}
      env:
        "WASME_USERNAME": "${{ secrets.WASME_USERNAME }}"
        "WASME_PASSWORD": "${{ secrets.WASME_PASSWORD }}"
