name: build-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  "BASEIMAGE": "webassemblyhub.io/thesisworker/"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Install WASME"
      run: |
        curl -sL https://run.solo.io/wasme/install | sh
    - name: Build
      run: |
        rustup update
        rustup target add wasm32-unknown-unknown
        cargo build --target wasm32-unknown-unknown --release --verbose
    - name: Run tests
      run: "echo TODO make tests work" #cargo test --verbose
    - name: "Set image version"
      id: set-image-tag
      run: |
        export IMAGE="${BASEIMAGE}:$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
        echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
        echo "::set-output name=IMAGE::${IMAGE}"
    - name: "Build WASM OCI image"
      run: ~/.wasme/bin/wasme build precompiled target/wasm32-unknown-unknown/release/authn-filter.wasm --tag ${IMAGE}
    - name: "Push WASM OCI image"
      run: |
        "~/.wasme/bin/wasme login -u $WASME_USERNAME -p $WASME_PASSWORD"
        wasme push ${IMAGE}
      env:
        "WASME_USERNAME": "${{ secrets.WASME_USERNAME }}"
        "WASME_PASSWORD": "${{ secrets.WASME_PASSWORD }}"
