name: build-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  "BASEIMAGE": "webassemblyhub.io/thesisworker/"
  ACLFLAGS: "-no-pie"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Versions
      run: |
        clang -v
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
    - name: "Install WASME"
      run: |
        curl -sL https://run.solo.io/wasme/install | sh
        echo "$HOME/.wasme/bin/" >> $GITHUB_PATH
    - name: setup env
      run: |
        cargo install cargo-wasi
    - name: Build
      run: make release
    - name: "Build WASM OCI image"
      run: make build-image # -e IMAGE=${IMAGE}
    - name: "Push WASM OCI image"
      run: |
        make wasme-login
        make push-image
      env:
        "WASME_USERNAME": "${{ secrets.WASME_USERNAME }}"
        "WASME_PASSWORD": "${{ secrets.WASME_PASSWORD }}"
